version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: addressdb
    ports:
      - 5432:5432
    volumes:
      - addressdb:/var/lib/postgresql/data
volumes:
  addressdb:
