version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: book
    ports:
      - 5432:5432
    volumes:
      - bookdb:/var/lib/postgresql/data
volumes:
  bookdb:
